import "@styles/globals.css";
import { Nav, Provider } from "@components";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
export const metadata = {
  title: "My App",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/icons/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <div className="main">
            <div className="gradient" />
          </div>
          <Nav />
          <main className="app">{children}</main>
          <ToastContainer />
        </Provider>
      </body>
    </html>
  );
}
